"""
Athena -> Hermes bridge: render a Plan AST into a cex-Hermes master-plan .md.

Per the operator's choice (master-plan bridge): Athena stays the deterministic front +
seams; the EXISTING Hermes PLAN_RUN (tools/hermes_plan_runner.py) executes. We emit the
exact format that runner parses — YAML frontmatter (plan_id/owner strict) + a `## Tasks`
section of `- [ ] task_id:` blocks, each naming a Hermes `workflow:`.

Mismatch the bridge resolves: Athena tasks carry a `success_check` shell command + a phase
DAG; Hermes tasks name a `workflow:` and run from a PRIORITY queue (no hard DAG). So each
Athena task -> `workflow: ATHENA_TASK` with `success_check` in `inputs`, and the phase DAG
is TOPO-SORTED into ascending `priority` so the runner processes in dependency order.
Hard dependency BLOCKING lives in the bd path (option B), not here — the honest trade-off
of choosing the .md bridge.

Pure: no I/O, no time. `created` is injected (the CLI stamps the date) so this stays
deterministic + golden-able.
"""
from __future__ import annotations

import json
import re

from lib.ast import Plan, Phase
from lib.plan2beads import _slugify


def _first_sentence(text: str) -> str:
    # split on a period FOLLOWED BY whitespace — so "athena.py" is not a sentence end
    return re.split(r"(?<=\.)\s", text.strip(), maxsplit=1)[0] if text.strip() else text


def _topo_order(phases: tuple[Phase, ...]) -> list[Phase]:
    """Kahn's algorithm with document-order tiebreak (deterministic). On a cycle, falls
    back to document order — cycles are caught upstream by seam.ast_wellformed."""
    by_key = {p.key: p for p in phases}
    keyset = set(by_key)
    indeg = {p.key: sum(1 for d in p.depends_on if d in keyset) for p in phases}
    doc = [p.key for p in phases]
    order: list[str] = []
    seen: set[str] = set()
    while len(order) < len(phases):
        nxt = next((k for k in doc if k not in seen and indeg[k] == 0), None)
        if nxt is None:                       # cycle — append remaining in document order
            nxt = next(k for k in doc if k not in seen)
        order.append(nxt)
        seen.add(nxt)
        for p in phases:
            if nxt in p.depends_on and indeg[p.key] > 0:
                indeg[p.key] -= 1
    return [by_key[k] for k in order]


def render_master_plan(plan: Plan, *, plan_id: str | None = None, owner: str = "divnjl2",
                       risk_tier: str = "T2", goal: str | None = None,
                       acceptance: str | None = None, task_workflow: str = "ATHENA_TASK",
                       created: str = "") -> str:
    """Plan AST -> cex-Hermes master-plan .md (consumed by hermes_plan_runner / PLAN_RUN)."""
    pid = plan_id or _slugify(plan.title)
    goal = goal or (_first_sentence(plan.overview) if plan.overview else plan.title)
    acceptance = acceptance or "every task's success_check exits 0"

    out: list[str] = ["---", f"plan_id: {pid}"]
    if created:
        out.append(f"created: {created}")
    out += [f"owner: {owner}", f"risk_tier: {risk_tier}", "requires_approval: false",
            "generated_by: athena", "---", ""]
    out += [f"# {plan.title} — {goal}", "", "## Goal (one sentence)", goal, "",
            "## Acceptance (one criterion)", acceptance, ""]
    if plan.out_of_scope:
        out.append("## Non-goals (explicit)")
        out += [f"- NO {s}" for s in plan.out_of_scope]
        out.append("")
    out += ["## Tasks", ""]

    prio = 0
    for ph in _topo_order(plan.phases):
        for t in ph.tasks:
            inputs: dict[str, str] = {"success_check": t.success_check, "title": t.title,
                                      "phase": ph.key}
            if t.files:
                inputs["files"] = ",".join(t.files)
            if t.autonomy and t.autonomy != "default":
                inputs["autonomy"] = t.autonomy
            out += [f"- [ ] task_id: {t.id}",
                    f"  workflow: {task_workflow}",
                    "  dispatcher: script",
                    f"  inputs: {json.dumps(inputs, ensure_ascii=False, sort_keys=True)}",
                    f"  priority: {prio}",
                    "  max_retries: 2"]
            if t.parallel:
                out.append("  # [P] parallelizable within phase")
            out.append("")
        prio += 1

    out += ["## Linked", f"- generated by Athena `compile` from front `{pid}`",
            "- executor: `apps/hermes/workflows/PLAN_RUN.yaml` (existing)", ""]
    return "\n".join(out)
